### ISSUE TITLE
Bold gradient not serialized/deserialized correctly

### ISSUE THREAD

**Issue by DSeeLP** [KyoriPowered/adventure-text-minimessage#193] opened 2021-11-18 21:38 UTC
When serializing a bold gradient a closing tag for a color is appended multiple times to the end.

![grafik](https://user-images.githubusercontent.com/46624152/142500644-ec4b113d-e704-4a7e-a8cd-9e481263152b.png)

The code used and the output is in the gist.
https://gist.github.com/DSeeLP/8ded7f84b84f55f9cf9edfdfd6ff8bd4

**Comment by DSeeLP** [comment] 2021-11-18 21:41
This applies to other decorations too.

Strikethrough
![grafik](https://user-images.githubusercontent.com/46624152/142501048-c9f2cb30-8af3-4c32-b2d1-fb4c163ad908.png)

Underlined
![grafik](https://user-images.githubusercontent.com/46624152/142501166-7d404d58-9092-4ec6-9310-eee444005c78.png)

These where the only ones i tested it probably applies to all decorations

**Comment by kezz** [comment] 2021-11-18 22:24
Duplicate of #192.

**Closed by kezz** 2021-11-18 22:24 UTC
Labels: type: bug
